import { tool } from 'ai';
import { z } from 'zod';

export const listenPodcast = tool({
  description: `Play Shrey's podcast. When the user asks to listen to the shrey's podcast, 
  call this tool WITHOUT any parameters to render an audio player, 
  it will talk about shrey's background, experience, and expertise in AI/ML.
  it's not just a resume, it's a podcast about shrey's background, experience, and expertise in AI/ML.
  This podcast itself is generated by a voice model but the guest is shrey, and uses shrey's voice model.`,
  inputSchema: z.object({}).optional(),
  execute: async () => {
    return {
      type: 'audio',
      src: '/podcast.mp3',
      title: 'Shrey Shah Podcast',
    } as const;
  },
});


